### ISSUE TITLE
Include flattened CAF files into ICARUS production chain

### ISSUE THREAD

**Issue by PetrilloAtWork** [SBNSoftware/sbnutil#3]
"Flat" CAF files are produced in the process of standard production _for SBND_.
Currently the tools to make it happen are in SBND repositories.
This issue tracks the progress to port that code here in `sbnutil` or in an equivalent, proper shared SBN repository and integrate the flattening step into ICARUS production chain as well whenever CAF files are produced.

**Comment by PetrilloAtWork** [comment]
My understanding is that main characters in this play are so far:
* SBN production team (@mayawos, Mateus) for the integration in the workflow
* @etyley for authorship and maintenance of the flattening script configuration for SBN

**Comment by etyley** [comment]
Although I originally wrote this script, I have since stepped down from the production team so someone there will have to take over maintenance.

**Comment by wesketchum** [comment]
@PetrilloAtWork @gputnam I think this has happened? If so, can we close? Or maybe need a new more specific issue?

**Comment by PetrilloAtWork** [comment]
Yes, it happened because somebody did it, and I don't remember whom to thank for it.
Anyway: thank you, mysterious benefactor!

**Comment by cerati** [comment]
Looks like this was done, so I marking it accordingly and closing
